/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

<<<<<<< refs/remotes/origin/melle
=======
//import Cliente.Cliente;
import Servidor.Servidor;

import java.io.IOException;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

>>>>>>> local
/**
 *
 * @author Enrique Rodriguez
 */
public class FrmInicio extends javax.swing.JFrame {

<<<<<<< refs/remotes/origin/melle
=======
    FrmConfigurarPartida crearPartida;
    private static FrmInicio menuS;
    private Servidor servidor;

>>>>>>> local
    /**
     * Creates new form PantallaInicio
     */
    public FrmInicio() {
        initComponents();
<<<<<<< refs/remotes/origin/melle
    }
=======
        crearPartida = new FrmConfigurarPartida();
        // Conectar automáticamente al servidor cuando se inicia la interfaz
//        iniciarServidor();

    }

    public static FrmInicio getInstance() {
        if (menuS == null) {
            menuS = new FrmInicio();
        }
        return menuS;
    }


>>>>>>> local

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIniciarPartida = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnUnirse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(200, 147, 108));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patolli");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 281, 59));

        btnIniciarPartida.setText("Crear partida");
        jPanel1.add(btnIniciarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 230, 60));

        btnSalir.setText("Salir");
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 230, 61));

        btnUnirse.setText("Unirse a partida");
        jPanel1.add(btnUnirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 230, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< refs/remotes/origin/melle
=======
    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
         try {
            new Thread(() -> {
                try {
                    SwingUtilities.invokeLater(() -> {
                        crearPartida.setVisible(true);
                        JOptionPane.showMessageDialog(this, "Partida creada con éxito. Esperando jugadores...");
                        setVisible(false);
                    });
                } catch (Exception e) {
                    SwingUtilities.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
                    });
                    e.printStackTrace();
                }
            }).start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    private void btnReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReglasActionPerformed
       dispose();
        DlgReglas control = new DlgReglas();
        control.setVisible(true);
    }//GEN-LAST:event_btnReglasActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        String[] botones = {"Si", "No"};
        int variable = JOptionPane.showOptionDialog(null, "¿Desea cerrar el juego?",
                "Confirmación", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, botones, botones[0]);
        if (variable == 0) {
            dispose();
        }
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseActionPerformed
        new Thread(() -> {
            try {
                Socket socket = new Socket("localhost", 50065);
                JOptionPane.showMessageDialog(this, "Conexión exitosa a la partida.");

                FrmUnirse frmUnirsePartida = new FrmUnirse();
                frmUnirsePartida.setVisible(true);
                this.dispose();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al conectarse a la partida: " + e.getMessage());
            }
        }).start();
    }//GEN-LAST:event_btnUnirseActionPerformed

>>>>>>> local
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUnirse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
