package Pantallas;

import PatolliCliente.ClienteControlador;
import com.chat.tcpcommons.Message;
import com.chat.tcpcommons.MessageBody;
import com.chat.tcpcommons.MessageType;
import entidades.Jugador;
import java.awt.Color;
import javax.swing.JOptionPane;
import tablero.Tablero;

/**
 *
 * @author esmeraldamolinaestrada
 */
public class FrmUnirse extends javax.swing.JFrame {

//    private ClienteControlador clienteControlador = new ClienteControlador();
    FrmInicio frmInicio;

    /**
     * Creates new form FrmUnirse
     */
    public FrmUnirse(FrmInicio frmInicio) {
        initComponents();
        this.frmInicio = frmInicio;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        txtCodigoPartida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("UNIRSE");

        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(txtCodigoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodigoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

//        try {
//            // Obtener el código de la sala desde el campo de texto
//            String codigoSala = txtCodigoPartida.getText();
//
//            // Validar que el código no esté vacío
//            if (codigoSala.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "Por favor ingresa un código de sala");
//                return;
//            }
//
//            // Crear el cuerpo del mensaje para unirse a la sala
//            MessageBody body = new MessageBody();
//            body.setCodigoSala(codigoSala);
//
//            // Crear el mensaje para unirse a la sala
//            Jugador jugador = new Jugador("Jugador 3", Color.BLUE); // Ajusta el nombre y color
//            Message mensajeUnirseSala = new Message.Builder()
//                    .messageType(MessageType.UNIRSE_SALA)
//                    .body(body)
//                    .build();
//
//            // Conectar al servidor
//            clienteControlador.iniciarConexion();
//            clienteControlador.enviarMensaje(mensajeUnirseSala);
//
//            // Esperar respuesta del servidor con el estado del tablero
//            Message mensajeEstadoTablero = clienteControlador.recibirMensaje();
//
//            // Verificar si el mensaje recibido es de tipo "ESTADO_TABLERO"
//            if (mensajeEstadoTablero.getMessageType() == MessageType.TABLERO_ACTUALIZADO) {
//                // Obtener el estado del tablero
//                MessageBody bodyTablero = (MessageBody) mensajeEstadoTablero.getContent();
//                Tablero estadoTablero = bodyTablero.getEstadoTablero(); // El tablero actual
//
//                // Verificar si el juego ya ha iniciado
//                if (!estadoTablero.isJuegoInicia()) {
//                    // El juego no ha iniciado, el jugador puede unirse
//                    // Crear el FrmTablero y pasarlo al nuevo tablero
//                    FrmTablero frmTablero = new FrmTablero(estadoTablero, clienteControlador);
//                    frmTablero.setVisible(true);
//
//                    // Cerrar la ventana actual de "Unirse"
//                    dispose();
//                } else {
//                    // El juego ya ha comenzado
//                    JOptionPane.showMessageDialog(this, "El juego ya ha comenzado, no puedes unirte.");
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Error: No se pudo obtener el estado del tablero.");
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Error al unirse a la sala: " + e.getMessage());
//        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmUnirse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmUnirse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmUnirse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmUnirse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmUnirse().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCodigoPartida;
    // End of variables declaration//GEN-END:variables
}
